services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq_btg
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./btg_dados:/var/lib/rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=123456